// mockData.js
export const generateMockData = () => {
  const today = new Date();
  
  const getRelativeDate = (daysDiff) => {
    const date = new Date(today);
    date.setDate(date.getDate() + daysDiff);
    return date.toISOString();
  };

  const getBirthDate = (age) => {
    const date = new Date(today);
    date.setFullYear(date.getFullYear() - age);
    return date.toISOString();
  };
  
  return [
    { 
      id: 1, 
      title: 'Felix har følelser', 
      author: 'Charlotte Mjelde', 
      borrower: {
        id: 'N0012345',
        name: 'Ole Nordmann',
        email: 'ole.nordmann@example.com',
        phone: '91234567',
        address: 'Bibliotekveien 123, 1234 Oslo',
        birthDate: getBirthDate(35),
        totalBooks: 12,
        averageRentalTime: 14,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jo Nesbø', 'Lars Saabye Christensen', 'Anne Holt']
      },
      reservedDate: getRelativeDate(-5),
      readyDate: getRelativeDate(-4),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'A-123',
      createdAt: getRelativeDate(-6),
      updatedAt: getRelativeDate(-2)
    },
    { 
      id: 2, 
      title: 'De står i kø', 
      author: 'Per Dybvig', 
      borrower: {
        id: 'N0023456',
        name: 'Kari Nordmann',
        email: 'kari.nordmann@example.com',
        phone: '92345678',
        address: 'Kolbotnveien 45, 1410 Kolbotn',
        birthDate: getBirthDate(28),
        totalBooks: 8,
        averageRentalTime: 10,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Jørn Lier Horst', 'Unni Lindell', 'Karin Fossum']
      },
      reservedDate: getRelativeDate(-7),
      readyDate: getRelativeDate(-6),
      pickedUpDate: getRelativeDate(-3),
      status: 'HENTET',
      pickupNumber: 'A-124',
      createdAt: getRelativeDate(-8),
      updatedAt: getRelativeDate(-3)
    },
    { 
      id: 3, 
      title: 'Harukkas ønske', 
      author: 'Malin Falch', 
      borrower: {
        id: 'N0034567',
        name: 'Petter Hansen',
        email: 'petter.hansen@example.com',
        phone: '93456789',
        address: 'Skiensveien 78, 1400 Ski',
        birthDate: getBirthDate(42),
        totalBooks: 15,
        averageRentalTime: 12,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Erika Fatland', 'Åsne Seierstad', 'Karl Ove Knausgård']
      },
      reservedDate: getRelativeDate(-3),
      readyDate: getRelativeDate(-2),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'A-125',
      createdAt: getRelativeDate(-4),
      updatedAt: getRelativeDate(-2)
    },
    { 
      id: 4, 
      title: 'Nekromanseren', 
      author: 'Victor Sotberg', 
      borrower: {
        id: 'N0045678',
        name: 'Marte Kirkerud',
        email: 'marte.kirkerud@example.com',
        phone: '94567890',
        address: 'Kolbotnveien 12, 1410 Kolbotn',
        birthDate: getBirthDate(31),
        totalBooks: 6,
        averageRentalTime: 9,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Herborg Kråkevik', 'Victor Sotberg', 'Jørgine Massa Vasstrand']
      },
      reservedDate: getRelativeDate(-5),
      readyDate: getRelativeDate(-4),
      pickedUpDate: getRelativeDate(-3),
      status: 'HENTET',
      pickupNumber: 'A-126',
      createdAt: getRelativeDate(-6),
      updatedAt: getRelativeDate(-3)
    },
    { 
      id: 5, 
      title: 'Den store boka om gaming', 
      author: 'Aslak Maurstad', 
      borrower: {
        id: 'N0056789',
        name: 'Lars Holm',
        email: 'lars.holm@example.com',
        phone: '95678901',
        address: 'Skiensveien 34, 1400 Ski',
        birthDate: getBirthDate(39),
        totalBooks: 9,
        averageRentalTime: 11,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Lars Kepler', 'Håkan Nesser', 'Henning Mankell']
      },
      reservedDate: getRelativeDate(-3),
      readyDate: getRelativeDate(-2),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'A-127',
      createdAt: getRelativeDate(-4),
      updatedAt: getRelativeDate(-2)
    },
    { 
      id: 6, 
      title: 'Max Manus', 
      author: 'Andreas Iversen', 
      borrower: {
        id: 'N0067890',
        name: 'Sofia Berg',
        email: 'sofia.berg@example.com',
        phone: '96789012',
        address: 'Kolbotnveien 89, 1410 Kolbotn',
        birthDate: getBirthDate(25),
        totalBooks: 7,
        averageRentalTime: 8,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Charlotte Mjelde', 'Andreas Iversen', 'Lene Ask']
      },
      reservedDate: getRelativeDate(-8),
      readyDate: getRelativeDate(-7),
      pickedUpDate: getRelativeDate(-6),
      status: 'HENTET',
      pickupNumber: 'A-128',
      createdAt: getRelativeDate(-9),
      updatedAt: getRelativeDate(-6)
    },
    { 
      id: 7, 
      title: 'Mysteriet med den tause papegøyen', 
      author: 'Lars Mæhle', 
      borrower: {
        id: 'N0078901',
        name: 'Erik Lund',
        email: 'erik.lund@example.com',
        phone: '97890123',
        address: 'Skiensveien 56, 1400 Ski',
        birthDate: getBirthDate(33),
        totalBooks: 11,
        averageRentalTime: 13,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jo Nesbø', 'Jørn Lier Horst', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-1),
      readyDate: getRelativeDate(0), // Today
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'A-129',
      createdAt: getRelativeDate(-2),
      updatedAt: getRelativeDate(0)
    },
    { 
      id: 8, 
      title: 'Min første bakebok', 
      author: 'Anne Nilsen og Elin Vatnar Vålaug', 
      borrower: {
        id: 'N0089012',
        name: 'Anna Dahl',
        email: 'anna.dahl@example.com',
        phone: '98901234',
        address: 'Kolbotnveien 23, 1410 Kolbotn',
        birthDate: getBirthDate(29),
        totalBooks: 5,
        averageRentalTime: 7,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Erika Fatland', 'Åsne Seierstad', 'Elin Vatnar Vålaug']
      },
      reservedDate: getRelativeDate(-6),
      readyDate: getRelativeDate(-5),
      pickedUpDate: getRelativeDate(-4),
      status: 'HENTET',
      pickupNumber: 'A-130',
      createdAt: getRelativeDate(-7),
      updatedAt: getRelativeDate(-4)
    },
    { 
      id: 9, 
      title: 'Livet er livsfarlig!', 
      author: 'Reidar Müller', 
      borrower: {
        id: 'N0090123',
        name: 'Thomas Olsen',
        email: 'thomas.olsen@example.com',
        phone: '99012345',
        address: 'Skiensveien 12, 1400 Ski',
        birthDate: getBirthDate(45),
        totalBooks: 14,
        averageRentalTime: 15,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Lars Saabye Christensen', 'Karin Fossum', 'Reidar Müller']
      },
      reservedDate: getRelativeDate(-10),
      readyDate: getRelativeDate(-9),
      pickedUpDate: null,
      status: 'UTLØPT',
      pickupNumber: 'A-131',
      createdAt: getRelativeDate(-11),
      updatedAt: getRelativeDate(-1)
    },
    { 
      id: 10, 
      title: 'Operasjon Ellemelle', 
      author: 'Jørn Lier Horst', 
      borrower: {
        id: 'N0010123',
        name: 'Maria Johansen',
        email: 'maria.johansen@example.com',
        phone: '90123456',
        address: 'Kolbotnveien 67, 1410 Kolbotn',
        birthDate: getBirthDate(27),
        totalBooks: 10,
        averageRentalTime: 9,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Jørn Lier Horst', 'Lars Mæhle', 'Charlotte Mjelde']
      },
      reservedDate: getRelativeDate(-4),
      readyDate: getRelativeDate(-3),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'A-132',
      createdAt: getRelativeDate(-5),
      updatedAt: getRelativeDate(-3)
    },
    {
      id: 11,
      title: "Jakten på Trolløyet",
      author: 'Jørn Lier Horst',
      borrower: {
        id: 'N0011234',
        name: 'Aaliyah Osman',
        email: 'aaliyah.osman@gmail.com',
        phone: '47223344',
        address: 'Solhøyveien 3A, 1406 Ski',
        birthDate: getBirthDate(22),
        totalBooks: 2,
        averageRentalTime: 5,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jørn Lier Horst', 'Charlotte Mjelde', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-2),
      readyDate: getRelativeDate(-1),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'NF-101',
      createdAt: getRelativeDate(-3),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 12,
      title: 'Jakten på Den hvite ørnen',
      author: 'Jørn Lier Horst',
      borrower: {
        id: 'N0012345',
        name: 'Marcus Li',
        email: 'marcus.li@outlook.com',
        phone: '47334455',
        address: 'Kolbotnveien 41B, 1410 Kolbotn',
        birthDate: getBirthDate(28),
        totalBooks: 7,
        averageRentalTime: 10,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Jørn Lier Horst', 'Anne Holt', 'Simon Sinek']
      },
      reservedDate: getRelativeDate(-5),
      readyDate: getRelativeDate(-3),
      pickedUpDate: getRelativeDate(-1),
      status: 'HENTET',
      pickupNumber: 'NF-102',
      createdAt: getRelativeDate(-6),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 13,
      title: 'Operasjon Traktor',
      author: 'Jørn Lier Horst',
      borrower: {
        id: 'N0013456',
        name: 'Yasmin Rahimi',
        email: 'yasmin.rahimi@hotmail.com',
        phone: '47445566',
        address: 'Langhusveien 55C, 1405 Langhus',
        birthDate: getBirthDate(36),
        totalBooks: 10,
        averageRentalTime: 14,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jørn Lier Horst', 'Lars Mæhle', 'Anne Holt']
      },
      reservedDate: getRelativeDate(-7),
      readyDate: getRelativeDate(-6),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'NF-103',
      createdAt: getRelativeDate(-8),
      updatedAt: getRelativeDate(-6)
    },
    {
      id: 14,
      title: 'Den store boken om Corny',
      author: 'Sandra Lyng',
      borrower: {
        id: 'N0014567',
        name: 'Elias Haddad',
        email: 'elias.haddad@mail.com',
        phone: '47556677',
        address: 'Oppegårdveien 9, 1415 Oppegård',
        birthDate: getBirthDate(46),
        totalBooks: 12,
        averageRentalTime: 9,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Sandra Lyng', 'Per Dybvig', 'Malin Falch']
      },
      reservedDate: getRelativeDate(-10),
      readyDate: getRelativeDate(-9),
      pickedUpDate: getRelativeDate(-7),
      status: 'HENTET',
      pickupNumber: 'NF-104',
      createdAt: getRelativeDate(-11),
      updatedAt: getRelativeDate(-7)
    },
    {
      id: 15,
      title: 'Jakten på Vinterstjernen',
      author: 'Jørn Lier Horst og Hans Jørgen Sandnes',
      borrower: {
        id: 'N0015678',
        name: 'Selma Ahmed',
        email: 'selma.ahm3d@gmail.com',
        phone: '47667788',
        address: 'Bøhlerveien 18, 1407 Vinterbro',
        birthDate: getBirthDate(18),
        totalBooks: 3,
        averageRentalTime: 4,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jørn Lier Horst', 'Hans Jørgen Sandnes', 'Charlotte Mjelde']
      },
      reservedDate: getRelativeDate(-1),
      readyDate: null,
      pickedUpDate: null,
      status: 'RESERVERT',
      pickupNumber: 'NF-105',
      createdAt: getRelativeDate(-1),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 16,
      title: 'Edderkoppenes dronning',
      author: 'Arne Lindmo',
      borrower: {
        id: 'N0016789',
        name: 'Tomás Fernandez',
        email: 'tomas.f@live.com',
        phone: '47778899',
        address: 'Skoleveien 12, 1413 Tårnåsen',
        birthDate: getBirthDate(39),
        totalBooks: 5,
        averageRentalTime: 8,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Arne Lindmo', 'Jørn Lier Horst', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-4),
      readyDate: getRelativeDate(-2),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'NF-106',
      createdAt: getRelativeDate(-5),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 17,
      title: 'Mine første ord',
      author: 'Knut Næsheim',
      borrower: {
        id: 'N0017890',
        name: 'Hanna Tran',
        email: 'hanna.tran@gmail.com',
        phone: '47889900',
        address: 'Hebekkveien 22, 1400 Ski',
        birthDate: getBirthDate(26),
        totalBooks: 9,
        averageRentalTime: 6,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Knut Næsheim', 'Anne Nilsen', 'Sandra Lyng']
      },
      reservedDate: getRelativeDate(-6),
      readyDate: getRelativeDate(-3),
      pickedUpDate: getRelativeDate(-1),
      status: 'HENTET',
      pickupNumber: 'NF-107',
      createdAt: getRelativeDate(-7),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 18,
      title: 'God natt, Bjørnis',
      author: 'Marthe Gravseth Aspen',
      borrower: {
        id: 'N0018901',
        name: 'Adrian Korsmo',
        email: 'adrian.korsmo@nmail.com',
        phone: '47990011',
        address: 'Fløisbonnveien 9, 1412 Sofiemyr',
        birthDate: getBirthDate(32),
        totalBooks: 6,
        averageRentalTime: 7,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Marthe Gravseth Aspen', 'Charlotte Mjelde', 'Knut Næsheim']
      },
      reservedDate: getRelativeDate(-3),
      readyDate: getRelativeDate(-1),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'NF-108',
      createdAt: getRelativeDate(-4),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 19,
      title: 'Vulkanen',
      author: 'Lars Mæhle',
      borrower: {
        id: 'N0019012',
        name: 'Naomi Mwangi',
        email: 'naomi.mwangi@example.com',
        phone: '47001122',
        address: 'Gamleveien 77, 1408 Kråkstad',
        birthDate: getBirthDate(42),
        totalBooks: 11,
        averageRentalTime: 9,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Lars Mæhle', 'Reidar Müller', 'Charlotte Mjelde']
      },
      reservedDate: getRelativeDate(-8),
      readyDate: getRelativeDate(-5),
      pickedUpDate: getRelativeDate(-2),
      status: 'HENTET',
      pickupNumber: 'NF-109',
      createdAt: getRelativeDate(-9),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 20,
      title: 'Forbannelsen i Trollskog',
      author: 'Arne Lindmo',
      borrower: {
        id: 'N0020123',
        name: 'Luca Moretti',
        email: 'luca.moretti@fastmail.com',
        phone: '47112233',
        address: 'Industriveien 4, 1414 Trollåsen',
        birthDate: getBirthDate(51),
        totalBooks: 14,
        averageRentalTime: 10,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Arne Lindmo', 'Lars Mæhle', 'Victor Sotberg']
      },
      reservedDate: getRelativeDate(-12),
      readyDate: getRelativeDate(-10),
      pickedUpDate: getRelativeDate(-9),
      status: 'HENTET',
      pickupNumber: 'NF-110',
      createdAt: getRelativeDate(-13),
      updatedAt: getRelativeDate(-9)
    },
    {
      id: 21,
      title: 'Stormen: Dinosaurgjengen: 13',
      author: 'Lars Mæhle',
      borrower: {
        id: 'N0021234',
        name: 'Jonas Berg',
        email: 'jonas.berg@gmail.com',
        phone: '47223344',
        address: 'Kolbotnveien 22, 1410 Kolbotn',
        birthDate: getBirthDate(40),
        totalBooks: 6,
        averageRentalTime: 11,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Lars Mæhle', 'Jørn Lier Horst', 'Arne Lindmo']
      },
      reservedDate: getRelativeDate(-5),
      readyDate: getRelativeDate(-3),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'B-101',
      createdAt: getRelativeDate(-6),
      updatedAt: getRelativeDate(-3)
    },
    {
      id: 22,
      title: 'Kokosbananas og juletyven',
      author: 'Rolf Magne Andersen og Victoria Haallman Hamre',
      borrower: {
        id: 'N0022345',
        name: 'Emma Svensson',
        email: 'emma.svensson@example.com',
        phone: '47334455',
        address: 'Skiveien 33, 1400 Ski',
        birthDate: getBirthDate(32),
        totalBooks: 4,
        averageRentalTime: 9,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Rolf Magne Andersen', 'Victoria Haallman Hamre', 'Charlotte Mjelde']
      },
      reservedDate: getRelativeDate(-2),
      readyDate: getRelativeDate(-1),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'B-102',
      createdAt: getRelativeDate(-3),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 23,
      title: 'Nord og ned',
      author: 'R. Kabicek, E. Skandfer og B. Agdestein',
      borrower: {
        id: 'N0023456',
        name: 'Mateo Garcia',
        email: 'mateo.garcia@hotmail.com',
        phone: '47445566',
        address: 'Langhusveien 10, 1405 Langhus',
        birthDate: getBirthDate(29),
        totalBooks: 8,
        averageRentalTime: 14,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['R. Kabicek', 'E. Skandfer', 'B. Agdestein']
      },
      reservedDate: getRelativeDate(-7),
      readyDate: getRelativeDate(-5),
      pickedUpDate: getRelativeDate(-2),
      status: 'HENTET',
      pickupNumber: 'B-103',
      createdAt: getRelativeDate(-8),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 24,
      title: 'Hvorfor kan man ikke sprekke av sinne?',
      author: 'Benjamin Baarli Silseth',
      borrower: {
        id: 'N0024567',
        name: 'Olivia Rahman',
        email: 'olivia.rahman@gmail.com',
        phone: '47556677',
        address: 'Oppegårdveien 45, 1415 Oppegård',
        birthDate: getBirthDate(37),
        totalBooks: 13,
        averageRentalTime: 16,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Benjamin Baarli Silseth', 'Charlotte Mjelde', 'Reidar Müller']
      },
      reservedDate: getRelativeDate(-4),
      readyDate: null,
      pickedUpDate: null,
      status: 'RESERVERT',
      pickupNumber: 'B-104',
      createdAt: getRelativeDate(-4),
      updatedAt: getRelativeDate(-4)
    },
    {
      id: 25,
      title: 'Fantus og verktøyene',
      author: 'Knut Næsheim',
      borrower: {
        id: 'N0025678',
        name: 'William Chen',
        email: 'william.chen@example.com',
        phone: '47667788',
        address: 'Vinterbrogata 8, 1407 Vinterbro',
        birthDate: getBirthDate(43),
        totalBooks: 10,
        averageRentalTime: 12,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Knut Næsheim', 'Anne Nilsen', 'Sandra Lyng']
      },
      reservedDate: getRelativeDate(-6),
      readyDate: getRelativeDate(-4),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'B-105',
      createdAt: getRelativeDate(-7),
      updatedAt: getRelativeDate(-4)
    },
    {
      id: 26,
      title: 'Felix har følelser',
      author: 'Charlotte Mjelde',
      borrower: {
        id: 'N0026789',
        name: 'Sofia Martinez',
        email: 'sofia.martinez@live.com',
        phone: '47778899',
        address: 'Tårnåsveien 16, 1413 Tårnåsen',
        birthDate: getBirthDate(35),
        totalBooks: 9,
        averageRentalTime: 13,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Charlotte Mjelde', 'Marthe Gravseth Aspen', 'Sandra Lyng']
      },
      reservedDate: getRelativeDate(-9),
      readyDate: getRelativeDate(-7),
      pickedUpDate: getRelativeDate(-5),
      status: 'HENTET',
      pickupNumber: 'B-106',
      createdAt: getRelativeDate(-10),
      updatedAt: getRelativeDate(-5)
    },
    {
      id: 27,
      title: 'Mysteriet med den tause papegøyen',
      author: 'Lars Mæhle',
      borrower: {
        id: 'N0027890',
        name: 'Noah Pedersen',
        email: 'noah.pedersen@gmail.com',
        phone: '47889900',
        address: 'Skiveien 89, 1400 Ski',
        birthDate: getBirthDate(30),
        totalBooks: 7,
        averageRentalTime: 10,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Lars Mæhle', 'Jørn Lier Horst', 'Per Dybvig']
      },
      reservedDate: getRelativeDate(-3),
      readyDate: getRelativeDate(-1),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'B-107',
      createdAt: getRelativeDate(-4),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 28,
      title: 'Operasjon Ellemelle',
      author: 'Jørn Lier Horst',
      borrower: {
        id: 'N0028901',
        name: 'Isabella Kim',
        email: 'isabella.kim@hotmail.com',
        phone: '47990011',
        address: 'Sofiemyrveien 22, 1412 Sofiemyr',
        birthDate: getBirthDate(28),
        totalBooks: 5,
        averageRentalTime: 8,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jørn Lier Horst', 'Charlotte Mjelde', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-7),
      readyDate: getRelativeDate(-5),
      pickedUpDate: null,
      status: 'UTLØPT',
      pickupNumber: 'B-108',
      createdAt: getRelativeDate(-8),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 29,
      title: 'Jakten på Vinterstjernen',
      author: 'Jørn Lier Horst og Hans Jørgen Sandnes',
      borrower: {
        id: 'N0029012',
        name: 'Lukas Andersen',
        email: 'lukas.andersen@example.com',
        phone: '47001122',
        address: 'Kråkstadveien 67, 1408 Kråkstad',
        birthDate: getBirthDate(38),
        totalBooks: 9,
        averageRentalTime: 11,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jørn Lier Horst', 'Hans Jørgen Sandnes', 'Arne Lindmo']
      },
      reservedDate: getRelativeDate(-5),
      readyDate: getRelativeDate(-2),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'B-109',
      createdAt: getRelativeDate(-6),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 30,
      title: 'Harukkas ønske',
      author: 'Malin Falch',
      borrower: {
        id: 'N0030123',
        name: 'Gabriel Rodriguez',
        email: 'gabriel.rodriguez@gmail.com',
        phone: '47112233',
        address: 'Trollåsveien 15, 1414 Trollåsen',
        birthDate: getBirthDate(44),
        totalBooks: 12,
        averageRentalTime: 15,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Malin Falch', 'Per Dybvig', 'Victor Sotberg']
      },
      reservedDate: getRelativeDate(-11),
      readyDate: getRelativeDate(-9),
      pickedUpDate: getRelativeDate(-8),
      status: 'HENTET',
      pickupNumber: 'B-110',
      createdAt: getRelativeDate(-12),
      updatedAt: getRelativeDate(-8)
    },
    {
      id: 31,
      title: 'Kokosbananas og juletyven',
      author: 'Rolf Magne Andersen og Victoria Haallman Hamre',
      borrower: {
        id: 'N0031234',
        name: 'Emilie Bakken',
        email: 'emilie.bakken@example.com',
        phone: '47223344',
        address: 'Kolbotnveien 103, 1410 Kolbotn',
        birthDate: getBirthDate(26),
        totalBooks: 4,
        averageRentalTime: 7,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Rolf Magne Andersen', 'Victoria Haallman Hamre', 'Charlotte Mjelde']
      },
      reservedDate: getRelativeDate(-2),
      readyDate: getRelativeDate(-1),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'C-101',
      createdAt: getRelativeDate(-3),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 32,
      title: 'Nekromanseren',
      author: 'Victor Sotberg',
      borrower: {
        id: 'N0032345',
        name: 'Daniel Jensen',
        email: 'daniel.jensen@hotmail.com',
        phone: '47334455',
        address: 'Skiveien 45, 1400 Ski',
        birthDate: getBirthDate(33),
        totalBooks: 8,
        averageRentalTime: 12,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Victor Sotberg', 'Jørn Lier Horst', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-8),
      readyDate: getRelativeDate(-6),
      pickedUpDate: getRelativeDate(-4),
      status: 'HENTET',
      pickupNumber: 'C-102',
      createdAt: getRelativeDate(-9),
      updatedAt: getRelativeDate(-4)
    },
    {
      id: 33,
      title: 'Max Manus',
      author: 'Andreas Iversen',
      borrower: {
        id: 'N0033456',
        name: 'Sophie Wang',
        email: 'sophie.wang@gmail.com',
        phone: '47445566',
        address: 'Langhusveien 78, 1405 Langhus',
        birthDate: getBirthDate(29),
        totalBooks: 6,
        averageRentalTime: 9,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Andreas Iversen', 'Anne Nilsen', 'Per Dybvig']
      },
      reservedDate: getRelativeDate(-3),
      readyDate: getRelativeDate(-1),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'C-103',
      createdAt: getRelativeDate(-4),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 34,
      title: 'Min første bakebok',
      author: 'Anne Nilsen og Elin Vatnar Vålaug',
      borrower: {
        id: 'N0034567',
        name: 'Adam Smith',
        email: 'adam.smith@outlook.com',
        phone: '47556677',
        address: 'Oppegårdveien 23, 1415 Oppegård',
        birthDate: getBirthDate(41),
        totalBooks: 15,
        averageRentalTime: 10,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Anne Nilsen', 'Elin Vatnar Vålaug', 'Knut Næsheim']
      },
      reservedDate: getRelativeDate(-7),
      readyDate: getRelativeDate(-5),
      pickedUpDate: getRelativeDate(-2),
      status: 'HENTET',
      pickupNumber: 'C-104',
      createdAt: getRelativeDate(-8),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 35,
      title: 'Livet er livsfarlig!',
      author: 'Reidar Müller',
      borrower: {
        id: 'N0035678',
        name: 'Maya Patel',
        email: 'maya.patel@example.com',
        phone: '47667788',
        address: 'Vinterbrogata 34, 1407 Vinterbro',
        birthDate: getBirthDate(34),
        totalBooks: 7,
        averageRentalTime: 11,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Reidar Müller', 'Benjamin Baarli Silseth', 'Charlotte Mjelde']
      },
      reservedDate: getRelativeDate(-6),
      readyDate: getRelativeDate(-3),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'C-105',
      createdAt: getRelativeDate(-7),
      updatedAt: getRelativeDate(-3)
    },
    {
      id: 36,
      title: 'Den store boka om gaming',
      author: 'Aslak Maurstad',
      borrower: {
        id: 'N0036789',
        name: 'Felix Nilsson',
        email: 'felix.nilsson@hotmail.com',
        phone: '47778899',
        address: 'Tårnåsveien 56, 1413 Tårnåsen',
        birthDate: getBirthDate(19),
        totalBooks: 3,
        averageRentalTime: 5,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Aslak Maurstad', 'Victor Sotberg', 'Sandra Lyng']
      },
      reservedDate: getRelativeDate(-5),
      readyDate: getRelativeDate(-2),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'C-106',
      createdAt: getRelativeDate(-6),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 37,
      title: 'De står i kø',
      author: 'Per Dybvig',
      borrower: {
        id: 'N0037890',
        name: 'Julie Ahmed',
        email: 'julie.ahmed@gmail.com',
        phone: '47889900',
        address: 'Hebekkveien 78, 1400 Ski',
        birthDate: getBirthDate(27),
        totalBooks: 5,
        averageRentalTime: 8,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Per Dybvig', 'Charlotte Mjelde', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-9),
      readyDate: getRelativeDate(-7),
      pickedUpDate: getRelativeDate(-5),
      status: 'HENTET',
      pickupNumber: 'C-107',
      createdAt: getRelativeDate(-10),
      updatedAt: getRelativeDate(-5)
    },
    {
      id: 38,
      title: 'Hvorfor kan man ikke sprekke av sinne?',
      author: 'Benjamin Baarli Silseth',
      borrower: {
        id: 'N0038901',
        name: 'Leo Sivertsen',
        email: 'leo.sivertsen@outlook.com',
        phone: '47990011',
        address: 'Fløisbonnveien 67, 1412 Sofiemyr',
        birthDate: getBirthDate(31),
        totalBooks: 9,
        averageRentalTime: 14,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Benjamin Baarli Silseth', 'Reidar Müller', 'Charlotte Mjelde']
      },
      reservedDate: getRelativeDate(-4),
      readyDate: getRelativeDate(-2),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'C-108',
      createdAt: getRelativeDate(-5),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 39,
      title: 'Fantus og verktøyene',
      author: 'Knut Næsheim',
      borrower: {
        id: 'N0039012',
        name: 'Sara Khan',
        email: 'sara.khan@example.com',
        phone: '47001122',
        address: 'Kråkstadveien 12, 1408 Kråkstad',
        birthDate: getBirthDate(36),
        totalBooks: 10,
        averageRentalTime: 13,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Knut Næsheim', 'Anne Nilsen', 'Elin Vatnar Vålaug']
      },
      reservedDate: getRelativeDate(-10),
      readyDate: getRelativeDate(-8),
      pickedUpDate: getRelativeDate(-6),
      status: 'HENTET',
      pickupNumber: 'C-109',
      createdAt: getRelativeDate(-11),
      updatedAt: getRelativeDate(-6)
    },
    {
      id: 40,
      title: 'God natt, Bjørnis',
      author: 'Marthe Gravseth Aspen',
      borrower: {
        id: 'N0040123',
        name: 'Jacob Olsen',
        email: 'jacob.olsen@gmail.com',
        phone: '47112233',
        address: 'Trollåsveien 89, 1414 Trollåsen',
        birthDate: getBirthDate(42),
        totalBooks: 11,
        averageRentalTime: 15,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Marthe Gravseth Aspen', 'Charlotte Mjelde', 'Sandra Lyng']
      },
      reservedDate: getRelativeDate(-3),
      readyDate: null,
      pickedUpDate: null,
      status: 'RESERVERT',
      pickupNumber: 'C-110',
      createdAt: getRelativeDate(-3),
      updatedAt: getRelativeDate(-3)
    },
    {
      id: 41,
      title: 'Vulkanen',
      author: 'Lars Mæhle',
      borrower: {
        id: 'N0041234',
        name: 'Nora Berg',
        email: 'nora.berg@hotmail.com',
        phone: '47223344',
        address: 'Kolbotnveien 12, 1410 Kolbotn',
        birthDate: getBirthDate(25),
        totalBooks: 6,
        averageRentalTime: 9,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Lars Mæhle', 'Jørn Lier Horst', 'Arne Lindmo']
      },
      reservedDate: getRelativeDate(-7),
      readyDate: getRelativeDate(-5),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'D-101',
      createdAt: getRelativeDate(-8),
      updatedAt: getRelativeDate(-5)
    },
    {
      id: 42,
      title: 'Jakten på Trolløyet',
      author: 'Jørn Lier Horst',
      borrower: {
        id: 'N0042345',
        name: 'Oscar Hansen',
        email: 'oscar.hansen@outlook.com',
        phone: '47334455',
        address: 'Skiveien 67, 1400 Ski',
        birthDate: getBirthDate(39),
        totalBooks: 14,
        averageRentalTime: 12,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jørn Lier Horst', 'Lars Mæhle', 'Charlotte Mjelde']
      },
      reservedDate: getRelativeDate(-6),
      readyDate: getRelativeDate(-4),
      pickedUpDate: getRelativeDate(-1),
      status: 'HENTET',
      pickupNumber: 'D-102',
      createdAt: getRelativeDate(-7),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 43,
      title: 'Forbannelsen i Trollskog',
      author: 'Arne Lindmo',
      borrower: {
        id: 'N0043456',
        name: 'Lucas Solheim',
        email: 'lucas.solheim@gmail.com',
        phone: '47445566',
        address: 'Langhusveien 34, 1405 Langhus',
        birthDate: getBirthDate(29),
        totalBooks: 7,
        averageRentalTime: 10,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Arne Lindmo', 'Lars Mæhle', 'Jørn Lier Horst']
      },
      reservedDate: getRelativeDate(-5),
      readyDate: getRelativeDate(-2),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'D-103',
      createdAt: getRelativeDate(-6),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 44,
      title: 'Jakten på Den hvite ørnen',
      author: 'Jørn Lier Horst',
      borrower: {
        id: 'N0044567',
        name: 'Ella Mikkelsen',
        email: 'ella.mikkelsen@example.com',
        phone: '47556677',
        address: 'Oppegårdveien 56, 1415 Oppegård',
        birthDate: getBirthDate(33),
        totalBooks: 9,
        averageRentalTime: 11,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jørn Lier Horst', 'Charlotte Mjelde', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-8),
      readyDate: getRelativeDate(-6),
      pickedUpDate: getRelativeDate(-3),
      status: 'HENTET',
      pickupNumber: 'D-104',
      createdAt: getRelativeDate(-9),
      updatedAt: getRelativeDate(-3)
    },
    {
      id: 45,
      title: 'Jakten på Vinterstjernen',
      author: 'Jørn Lier Horst og Hans Jørgen Sandnes',
      borrower: {
        id: 'N0045678',
        name: 'Emil Johansen',
        email: 'emil.johansen@gmail.com',
        phone: '47667788',
        address: 'Vinterbrogata 18, 1407 Vinterbro',
        birthDate: getBirthDate(37),
        totalBooks: 12,
        averageRentalTime: 14,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Jørn Lier Horst', 'Hans Jørgen Sandnes', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-4),
      readyDate: getRelativeDate(-2),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'D-105',
      createdAt: getRelativeDate(-5),
      updatedAt: getRelativeDate(-2)
    },
    {
      id: 46,
      title: 'Operasjon Traktor',
      author: 'Jørn Lier Horst',
      borrower: {
        id: 'N0046789',
        name: 'Alma Larsen',
        email: 'alma.larsen@outlook.com',
        phone: '47778899',
        address: 'Tårnåsveien 29, 1413 Tårnåsen',
        birthDate: getBirthDate(24),
        totalBooks: 5,
        averageRentalTime: 8,
        libraryAffiliation: 'Kolbtn',
        favoriteAuthors: ['Jørn Lier Horst', 'Charlotte Mjelde', 'Per Dybvig']
      },
      reservedDate: getRelativeDate(-9),
      readyDate: getRelativeDate(-7),
      pickedUpDate: getRelativeDate(-4),
      status: 'HENTET',
      pickupNumber: 'D-106',
      createdAt: getRelativeDate(-10),
      updatedAt: getRelativeDate(-4)
    },
    {
      id: 47,
      title: 'Den store boken om Corny',
      author: 'Sandra Lyng',
      borrower: {
        id: 'N0047890',
        name: 'Henrik Nielsen',
        email: 'henrik.nielsen@hotmail.com',
        phone: '47889900',
        address: 'Hebekkveien 45, 1400 Ski',
        birthDate: getBirthDate(28),
        totalBooks: 8,
        averageRentalTime: 13,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Sandra Lyng', 'Charlotte Mjelde', 'Knut Næsheim']
      },
      reservedDate: getRelativeDate(-2),
      readyDate: getRelativeDate(-1),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'D-107',
      createdAt: getRelativeDate(-3),
      updatedAt: getRelativeDate(-1)
    },
    {
      id: 48,
      title: 'Edderkoppenes dronning',
      author: 'Arne Lindmo',
      borrower: {
        id: 'N0048901',
        name: 'Sophia Lee',
        email: 'sophia.lee@gmail.com',
        phone: '47990011',
        address: 'Fløisbonnveien 34, 1412 Sofiemyr',
        birthDate: getBirthDate(32),
        totalBooks: 10,
        averageRentalTime: 9,
        libraryAffiliation: 'Kolbotn',
        favoriteAuthors: ['Arne Lindmo', 'Jørn Lier Horst', 'Lars Mæhle']
      },
      reservedDate: getRelativeDate(-6),
      readyDate: getRelativeDate(-3),
      pickedUpDate: null,
      status: 'VENTER',
      pickupNumber: 'D-108',
      createdAt: getRelativeDate(-7),
      updatedAt: getRelativeDate(-3)
    },
    {
      id: 49,
      title: 'Mine første ord',
      author: 'Knut Næsheim',
      borrower: {
        id: 'N0049012',
        name: 'Alexander Bakken',
        email: 'alexander.bakken@example.com',
        phone: '47001122',
        address: 'Kråkstadveien 90, 1408 Kråkstad',
        birthDate: getBirthDate(40),
        totalBooks: 13,
        averageRentalTime: 12,
        libraryAffiliation: 'Ski',
        favoriteAuthors: ['Knut Næsheim', 'Anne Nilsen', 'Sandra Lyng']
      },
      reservedDate: getRelativeDate(-3),
      readyDate: null,
      pickedUpDate: null,
      status: 'RESERVERT',
      pickupNumber: 'D-109',
      createdAt: getRelativeDate(-3),
      updatedAt: getRelativeDate(-3)
    },
    {
      id: 50,
      title: 'Nord og ned',
      author: 'R. Kabicek, E. Skandfer og B. Agdestein',
      borrower: {
        id: 'N0050123',
        name: 'Victoria Olsen',
        email: 'victoria.olsen@hotmail.com',
        phone: '47112233',
        address: 'Trollåsveien 45, 1414 Trollåsen',
        birthDate: getBirthDate(35),
        totalBooks: 11,
        averageRentalTime: 10,
        libraryAffiliation: 'Kolbtn',
        favoriteAuthors: ['R. Kabicek', 'E. Skandfer', 'B. Agdestein']
      },
      reservedDate: getRelativeDate(-7),
      readyDate: getRelativeDate(-5),
      pickedUpDate: getRelativeDate(-2),
      status: 'HENTET',
      pickupNumber: 'D-110',
      createdAt: getRelativeDate(-8),
      updatedAt: getRelativeDate(-2)
    }
  ];
};